[config]
number_of_cycles = 117
region_range = [2,6]
# 1: cubed, 2: squared, 3: splat, 4: sin, 5: ellipse
region_types = [1,1,1,1,2,2,2,2,3,4,4,4,4,5,5,5]
# enter your desired output path here (don't forget the ending "/"!!!)
out_path = "E:/Rust/Projects/OutPut Files/Regions/"
# input the path to your clean cluster file with all sectors that you want to add regions to
clean_cluster_file = "E:/Rust/Projects/OutPut Files/Regions/clusters no tags.xml"

[spline_cubed]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km, with a point every 10km
radius = [10000, 70000]
step_range = [-10, 10]
step_rate = 50000
# the next 4 values determine horizontal and vertical offset
# there is a "deadzone" variable to avoid regions snaking directly through the center of the sector all the time
# set values to -1 and 1 to effectively remove the deadzone if you wish
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
# width variance changes the shape of the curve somewhat; deadzone and variance are set here based on graphical testing
# numbers outside this range tend to create curves that are closer to lines and are generally unappealling
width_variance = [-500000000000.0, 500000000000.0]
width_deadzone = [-100000000.0, 100000000.0]
# just to give y some action.....
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_cubed.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog, 7: sound
region_objects =  [1,1,1,1,1,2,3,4,4,5,5,7]
region_count = [2,6]

[spline_cubed.fields.fields_mods]
# 1-3: very high ore, sil, niv
# 4-9 ore  10-14 sil  15-18 niv  19-23 ice
# larger asteroids have smaller numbers here
resource_roid_weight = [1,2,3,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,9,9,10,10,11,11,11,12,12,12,13,13,13,14,14,15,16,17,18,19,19,19,19,20,20,20,20,20,21,21,21,21,22,22,22,22,23,23]
# all xenon; larger asteroids have smaller numbers here
nonresource_roid_weight = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6,6]
#  1-4 generic ships, 5 stations
debris_weight = [1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5,6,7,8,9,10,11,12,13,13,14]
lockbox_weight = [1,2]
resource_neb_weight = [1,2,3,4]
positional_weight = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #many of these are broken, do not use
sound_weight = [1,2,3,4,5,6,7,8]
# multipliers are chosen at random between these values
density_factor = [0.3,0.8]
rotation = [0.9,1.1]
rotationvariation = [0.9,1.1]
noisescale = [0.9,1.1]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.0]
lateral_1 = [0.0,0.01]
lateral_2 = [0.01,0.3]
lateral_3 = [0.3,0.5]
lateral_4 = [0.5,0.7]
lateral_5 = [0.7,0.9]
radial_1 = [0.0,0.01]
radial_2 = [0.01,0.3]
radial_3 = [0.3,0.5]
radial_4 = [0.5,0.7]
radial_5 = [0.7,0.9]

[splat]
# radius value of circular region
radius = [400000, 500000]
# height value of circular region
linear = [200000, 300000]
# used to offset the region within the sector
# x_offset = [10000, 300000]
# z_offset = [10000, 300000]
[splat.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog, 7: sound
region_objects =  [1,1,1,1,1,3,4,4,5,5,7]
region_count = [2,4]

[splat.fields.fields_mods]
# 1-3: very high ore, sil, niv
# 4-9 ore  10-14 sil  15-18 niv  19-23 ice
# larger asteroids have smaller numbers here
resource_roid_weight = [1,2,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,9,9,10,10,11,11,11,12,12,12,13,13,13,14,19,19,19,19,20,20,20,20,20,21,21,21,21,22,22,22,22,23,23]
# all xenon; larger asteroids have smaller numbers here
nonresource_roid_weight = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6,6]
#  1-4 generic ships, 5 stations
debris_weight = [1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5,6,7,8,9,10,11,12,13,13,14]
lockbox_weight = [1,2]
resource_neb_weight = [1,2,3,4]
positional_weight = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #many of these are broken, do not use
sound_weight = [1,2,3,4,5,6,7,8]
density_factor = [0.15,0.4]
rotation = [0.9,1.1]
rotationvariation = [0.9,1.1]
noisescale = [0.9,1.1]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.0]
# 1 is the farthest out, 5 is center point
lateral_1 = [0.0,0.01]
lateral_2 = [0.01,0.3]
lateral_3 = [0.3,0.4]
lateral_4 = [0.4,0.5]
lateral_5 = [0.5,0.6]
radial_1 = [0.0,0.01]
radial_2 = [0.01,0.3]
radial_3 = [0.3,0.4]
radial_4 = [0.4,0.5]
radial_5 = [0.5,0.6]

[spline_squared]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km, with a point every 10km
radius = [10000, 50000]
step_range = [-10, 10]
step_rate = 50000
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
width_variance = [-7500000.0, 7500000.0]
width_deadzone = [-10000.0, 10000.0]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_squared.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog, 7: sound
region_objects =  [1,1,1,1,1,2,3,4,4,5,5,7]
region_count = [2,6]

[spline_squared.fields.fields_mods]
# 1-3: very high ore, sil, niv
# 4-9 ore  10-14 sil  15-18 niv  19-23 ice
# larger asteroids have smaller numbers here
resource_roid_weight = [1,2,3,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,9,9,10,10,11,11,11,12,12,12,13,13,13,14,14,15,16,17,18,19,19,19,19,20,20,20,20,20,21,21,21,21,22,22,22,22,23,23]
# all xenon; larger asteroids have smaller numbers here
nonresource_roid_weight = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6,6]
#  1-4 generic ships, 5 stations
debris_weight = [1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5,6,7,8,9,10,11,12,13,13,14]
lockbox_weight = [1,2]
resource_neb_weight = [1,2,3,4]
positional_weight = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #many of these are broken, do not use
sound_weight = [1,2,3,4,5,6,7,8]
density_factor = [0.3,0.8]
rotation = [0.9,1.1]
rotationvariation = [0.9,1.1]
noisescale = [0.9,1.1]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.0]
lateral_1 = [0.0,0.01]
lateral_2 = [0.01,0.3]
lateral_3 = [0.3,0.5]
lateral_4 = [0.5,0.7]
lateral_5 = [0.7,0.9]
radial_1 = [0.0,0.01]
radial_2 = [0.01,0.3]
radial_3 = [0.3,0.5]
radial_4 = [0.5,0.7]
radial_5 = [0.7,0.9]

[spline_sin]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km along the x axis, with a point every 10km
radius = [10000, 50000]
step_range = [-10, 10]
step_rate = 50000
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
width_variance = [-0.000006, 0.000006]
width_deadzone = [-0.000001, 0.000001]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_sin.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog, 7: sound
region_objects =  [1,1,1,1,1,2,3,4,4,5,5,7]
region_count = [2,6]

[spline_sin.fields.fields_mods]
# 1-3: very high ore, sil, niv
# 4-9 ore  10-14 sil  15-18 niv  19-23 ice
# larger asteroids have smaller numbers here
resource_roid_weight = [1,2,3,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,9,9,10,10,11,11,11,12,12,12,13,13,13,14,14,15,16,17,18,19,19,19,19,20,20,20,20,20,21,21,21,21,22,22,22,22,23,23]
# all xenon; larger asteroids have smaller numbers here
nonresource_roid_weight = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6,6]
#  1-4 generic ships, 5 stations
debris_weight = [1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5,6,7,8,9,10,11,12,13,13,14]
lockbox_weight = [1,2]
resource_neb_weight = [1,2,3,4]
positional_weight = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #many of these are broken, do not use
sound_weight = [1,2,3,4,5,6,7,8]
density_factor = [0.3,0.8]
rotation = [0.9,1.1]
rotationvariation = [0.9,1.1]
noisescale = [0.9,1.1]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.0]
lateral_1 = [0.0,0.01]
lateral_2 = [0.01,0.3]
lateral_3 = [0.3,0.5]
lateral_4 = [0.5,0.7]
lateral_5 = [0.7,0.9]
radial_1 = [0.0,0.01]
radial_2 = [0.01,0.3]
radial_3 = [0.3,0.5]
radial_4 = [0.5,0.7]
radial_5 = [0.7,0.9]

[spline_ellipse]
# radius value is for the width of the region (same as the way it's used elsewhere)
radius = [50000, 100000]
# how many steps the spline can roll: 15 = a full circle
step_range = [5, 15]
# what is the radius of the circle we're trying to make
ellipse_radius = [50000, 200000]
# starting_angle: measured in radians and determines the place in the circle where the steps begin. 0 is the origin, 2 comes back around to the same position.
starting_angle = [0, 2]
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_ellipse.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog, 7: sound
region_objects =  [1,1,1,1,1,2,3,4,4,5,5,7]
region_count = [2,6]

[spline_ellipse.fields.fields_mods]
# 1-3: very high ore, sil, niv
# 4-9 ore  10-14 sil  15-18 niv  19-23 ice
# larger asteroids have smaller numbers here
resource_roid_weight = [1,2,3,4,4,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8,8,9,9,10,10,11,11,11,12,12,12,13,13,13,14,14,15,16,17,18,19,19,19,19,20,20,20,20,20,21,21,21,21,22,22,22,22,23,23]
# all xenon; larger asteroids have smaller numbers here
nonresource_roid_weight = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6,6]
#  1-4 generic ships, 5 stations
debris_weight = [1,1,1,2,2,2,3,3,3,3,4,4,4,4,5,5,6,7,8,9,10,11,12,13,13,14]
lockbox_weight = [1,2]
resource_neb_weight = [1,2,3,4]
positional_weight = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #many of these are broken, do not use
sound_weight = [1,2,3,4,5,6,7,8]
density_factor = [0.2,0.8]
rotation = [0.9,1.1]
rotationvariation = [0.9,1.1]
noisescale = [0.9,1.1]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.0]
lateral_1 = [0.0,0.01]
lateral_2 = [0.01,0.3]
lateral_3 = [0.3,0.4]
lateral_4 = [0.4,0.5]
lateral_5 = [0.5,0.6]
radial_1 = [0.0,0.01]
radial_2 = [0.01,0.3]
radial_3 = [0.3,0.4]
radial_4 = [0.4,0.5]
radial_5 = [0.5,0.6]
