[config]
region_types = ["cubed", "squared", "splat", "sqrt", "cbrt"]
number_to_create = 10
out_path = "E:/Rust/Projects/OutPut Files/Regions/"

[spline_cubed]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km, with a point every 10km
radius = [10000, 50000]
step_range = [-50, 50]
step_rate = 10000
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
width_variance = [-100000000000, 100000000000]
width_deadzone = [-100000000, 100000000]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_cubed.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog
region_objects =  [1,2,3,4,5,6]
region_count = 10

[spline_cubed.fields.fields_mods]
density_factor = [0.1,1.5]
density_randomization = [0.1,1.5]
rotation = [0.1,1.5]
rotationvariation = [0.1,1.5]
noisescale = [0.1,1.5]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.5]
distancefactor = [0.1,1.5]

[splat]
radius = [50000, 100000]
linear = [10000, 100000]
[splat.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog
region_objects =  [1,2,3,4,5,6]
region_count = 10

[splat.fields.fields_mods]
density_factor = [0.1,1.5]
density_randomization = [0.1,1.5]
rotation = [0.1,1.5]
rotationvariation = [0.1,1.5]
noisescale = [0.1,1.5]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.5]
distancefactor = [0.1,1.5]

[spline_squared]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km, with a point every 10km
radius = [10000, 50000]
step_range = [-50, 50]
step_rate = 10000
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
width_variance = [-7500000, 7500000]
width_deadzone = [-10000, 10000]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_squared.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog
region_objects =  [1,2,3,4,5,6]
region_count = 10

[spline_squared.fields.fields_mods]
density_factor = [0.1,1.5]
density_randomization = [0.1,1.5]
rotation = [0.1,1.5]
rotationvariation = [0.1,1.5]
noisescale = [0.1,1.5]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.5]
distancefactor = [0.1,1.5]

[spline_sqrt]
# step_range * step_rate = the min and max x values for your region
# default is [-50, 50] and 10000 for a range of -500km to 500km, with a point every 10km
radius = [10000, 50000]
step_range = [-50, 50]
step_rate = 10000
h_offset_range = [-200000, 200000]
h_deadzone_range = [-100000, 100000]
v_offset_range = [-200000, 200000]
v_deadzone_range = [-100000, 100000]
width_variance = [-7500000, 7500000]
width_deadzone = [-10000, 10000]
y_values = [-10000,10000]
y_variance = [-100, 100]
[spline_sqrt.fields]
# 1: resource roids, 2: non-resource roids, 3: debris, 4: lockboxes, 5: resource fog, 6: non-resource fog
region_objects =  [1,2,3,4,5,6]
region_count = 10

[spline_sqrt.fields.fields_mods]
density_factor = [0.1,1.5]
density_randomization = [0.1,1.5]
rotation = [0.1,1.5]
rotationvariation = [0.1,1.5]
noisescale = [0.1,1.5]
minnoisevalue = [0.1,0.9]
maxnoisevalue = [0.9,1.5]
distancefactor = [0.1,1.5]



[user_gen_region]
point_a = [-200000, 0, 200000]
point_b = [-100000, 0, 100000]
point_c = [0, 0, 0]
point_d = [100000, 0, -100000]
point_e = [200000, 0, -200000]
length_variance = [1.0, 1.5]
