[[offset]]
cluster = "tppirate_Cluster_99_macro"
name = "tppirate_Cluster_99_Sector001_macro"
x=-69551432 
y=-92956129 
z=37579824
          
[[offset]]
cluster = "tppirate_Cluster_98_macro"
name = "tppirate_Cluster_98_Sector001_macro"
x=922704 
y=8737168 
z=-143198712
          
[[offset]]
cluster = "tppirate_Cluster_97_macro"
name = "tppirate_Cluster_97_Sector001_macro"
x=144698112 
y=64280928 
z=-175268498
          
[[offset]]
cluster = "tppirate_Cluster_96_macro"
name = "tppirate_Cluster_96_Sector001_macro"
x=-123007792 
y=36716164 
z=158596768
          
[[offset]]
cluster = "tppirate_Cluster_95_macro"
name = "tppirate_Cluster_95_Sector001_macro"
x=93543680 
y=3542040 
z=-172530382
          
[[offset]]
cluster = "tppirate_Cluster_94_macro"
name = "tppirate_Cluster_94_Sector001_macro"
x=75704288 
y=-98881957 
z=-123136456
          
[[offset]]
cluster = "tppirate_Cluster_93_macro"
name = "tppirate_Cluster_93_Sector001_macro"
x=-121957520 
y=-43550844 
z=-39861984
          
[[offset]]
cluster = "tppirate_Cluster_92_macro"
name = "tppirate_Cluster_92_Sector001_macro"
x=-188813525 
y=-85923512 
z=-49389440
          
[[offset]]
cluster = "tppirate_Cluster_91_macro"
name = "tppirate_Cluster_91_Sector001_macro"
x=55547840 
y=-73777748 
z=67167584
          
[[offset]]
cluster = "tppirate_Cluster_90_macro"
name = "tppirate_Cluster_90_Sector001_macro"
x=-896752 
y=-73149678 
z=50168752
          
[[offset]]
cluster = "tppirate_Cluster_89_macro"
name = "tppirate_Cluster_89_Sector001_macro"
x=-177411310 
y=9955360 
z=-175266266
          
[[offset]]
cluster = "tppirate_Cluster_88_macro"
name = "tppirate_Cluster_88_Sector001_macro"
x=-63388176 
y=-73727394 
z=156174400
          
[[offset]]
cluster = "tppirate_Cluster_87_macro"
name = "tppirate_Cluster_87_Sector001_macro"
x=-5536912 
y=61255104 
z=46995168
          
[[offset]]
cluster = "tppirate_Cluster_86_macro"
name = "tppirate_Cluster_86_Sector001_macro"
x=126801952 
y=-4361776 
z=102084960
          
[[offset]]
cluster = "tppirate_Cluster_85_macro"
name = "tppirate_Cluster_85_Sector001_macro"
x=-186857049 
y=65217824 
z=70408000
          
[[offset]]
cluster = "tppirate_Cluster_84_macro"
name = "tppirate_Cluster_84_Sector001_macro"
x=145483232 
y=60644384 
z=-38136464
          
[[offset]]
cluster = "tppirate_Cluster_83_macro"
name = "tppirate_Cluster_83_Sector001_macro"
x=78131904 
y=94523008 
z=-164410516
          
[[offset]]
cluster = "tppirate_Cluster_82_macro"
name = "tppirate_Cluster_82_Sector001_macro"
x=-184194438 
y=47307008 
z=-17024416
          
[[offset]]
cluster = "tppirate_Cluster_81_macro"
name = "tppirate_Cluster_81_Sector001_macro"
x=175764524 
y=-24952208 
z=109577408
          
[[offset]]
cluster = "tppirate_Cluster_80_macro"
name = "tppirate_Cluster_80_Sector001_macro"
x=189110656 
y=-55069852 
z=-40554288
          
[[offset]]
cluster = "meditech_Cluster_01_macro"
name = "meditech_Cluster_01_Sector001_macro"
x=109540960 
y=-77960534 
z=-189514724
          
[[offset]]
cluster = "tpthree_cluster1158_macro"
name = "tpthree_cluster1158_sector001_macro"
x=176075872 
y=83305904 
z=199971968
          
[[offset]]
cluster = "tpthree_cluster178_macro"
name = "tpthree_cluster178_sector001_macro"
x=189512928 
y=-56720312 
z=58742208
          
[[offset]]
cluster = "tpthree_cluster177_macro"
name = "tpthree_cluster177_sector001_macro"
x=161072 
y=70123440 
z=47633984
          
[[offset]]
cluster = "tpthree_cluster176_macro"
name = "tpthree_cluster176_sector001_macro"
x=-50514944 
y=86812352 
z=-122722832
          
[[offset]]
cluster = "tpthree_cluster195_macro"
name = "tpthree_cluster195_sector001_macro"
x=-39773600 
y=24581048 
z=7860320
          
[[offset]]
cluster = "tpthree_cluster196_macro"
name = "tpthree_cluster196_sector001_macro"
x=-94462040 
y=36535744 
z=98438368
          
[[offset]]
cluster = "tpthree_cluster215_macro"
name = "tpthree_cluster215_sector001_macro"
x=-68521968 
y=97783696 
z=48215120
          
[[offset]]
cluster = "tpthree_cluster110_macro"
name = "tpthree_cluster110_sector001_macro"
x=178280672 
y=40226208 
z=-119255968
          
[[offset]]
cluster = "tpthree_cluster1217_macro"
name = "tpthree_cluster1217_sector001_macro"
x=-6620496 
y=43776032 
z=147001088
          
[[offset]]
cluster = "tpthree_cluster307_macro"
name = "tpthree_cluster307_sector001_macro"
x=97505952 
y=76324768 
z=14091056
          
[[offset]]
cluster = "tpthree_cluster393_macro"
name = "tpthree_cluster393_sector001_macro"
x=-61470464 
y=26959920 
z=60675792
          
[[offset]]
cluster = "tpthree_cluster029_macro"
name = "tpthree_cluster029_sector001_macro"
x=46928928 
y=47412848 
z=20706840
          
[[offset]]
cluster = "tpthree_cluster035_macro"
name = "tpthree_cluster035_sector001_macro"
x=-97672032 
y=78035728 
z=-85143400
          
[[offset]]
cluster = "tpthree_cluster049_macro"
name = "tpthree_cluster049_sector001_macro"
x=99765216 
y=-49986072 
z=11137968
          
[[offset]]
cluster = "tpthree_cluster052_macro"
name = "tpthree_cluster052_sector001_macro"
x=-143846756 
y=83594352 
z=-89459504
          
[[offset]]
cluster = "tpthree_cluster064_macro"
name = "tpthree_cluster064_sector001_macro"
x=-157214044 
y=5687760 
z=-114351520
          
[[offset]]
cluster = "tpthree_cluster084_macro"
name = "tpthree_cluster084_sector001_macro"
x=135183328 
y=-97921638 
z=-128229416
          
[[offset]]
cluster = "tpthree_cluster085_macro"
name = "tpthree_cluster085_sector001_macro"
x=-85315680 
y=-57185848 
z=113889184
          
[[offset]]
cluster = "tpthree_cluster104_macro"
name = "tpthree_cluster104_sector001_macro"
x=-99845024 
y=-69174688 
z=-102232704
          
[[offset]]
cluster = "tpthree_cluster105_macro"
name = "tpthree_cluster105_sector001_macro"
x=14161680 
y=46990912 
z=5328352
          
[[offset]]
cluster = "tpthree_cluster142_macro"
name = "tpthree_cluster142_sector001_macro"
x=-49541216 
y=-15095760 
z=153943648
          
[[offset]]
cluster = "tpthree_cluster143_macro"
name = "tpthree_cluster143_sector001_macro"
x=158249184 
y=35341696 
z=14576048
          
[[offset]]
cluster = "tpthree_cluster183_macro"
name = "tpthree_cluster183_sector001_macro"
x=-183951584 
y=73001728 
z=113247584
          
[[offset]]
cluster = "tpthree_cluster185_macro"
name = "tpthree_cluster185_sector001_macro"
x=-108759424 
y=-85613941 
z=-41251104
          
[[offset]]
cluster = "tpthree_cluster188_macro"
name = "tpthree_cluster188_sector001_macro"
x=-153234096 
y=-99751150 
z=43411584
          
[[offset]]
cluster = "tpthree_cluster203_macro"
name = "tpthree_cluster203_sector001_macro"
x=15989632 
y=-28202808 
z=-87193056
          
[[offset]]
cluster = "tpthree_cluster204_macro"
name = "tpthree_cluster204_sector001_macro"
x=-119122288 
y=73292784 
z=-175314760
          
[[offset]]
cluster = "tpthree_cluster205_macro"
name = "tpthree_cluster205_sector001_macro"
x=-50899648 
y=65047456 
z=26119968
          
[[offset]]
cluster = "tpthree_cluster210_macro"
name = "tpthree_cluster210_sector001_macro"
x=135016608 
y=12413136 
z=57062432
          
[[offset]]
cluster = "tpthree_cluster217_macro"
name = "tpthree_cluster217_sector001_macro"
x=98684832 
y=-43895244 
z=-123388984
          
[[offset]]
cluster = "tpthree_cluster1220_macro"
name = "tpthree_cluster1220_sector001_macro"
x=177603808 
y=64214768 
z=20089200
          
[[offset]]
cluster = "tpthree_cluster227_macro"
name = "tpthree_cluster227_sector001_macro"
x=-64955456 
y=-22575816 
z=-87396088
          
[[offset]]
cluster = "tpthree_cluster234_macro"
name = "tpthree_cluster234_sector001_macro"
x=191816704 
y=-40420188 
z=31949280
          
[[offset]]
cluster = "tpthree_cluster1240_macro"
name = "tpthree_cluster1240_sector001_macro"
x=70262720 
y=3519104 
z=162467584
          
[[offset]]
cluster = "tpthree_cluster259_macro"
name = "tpthree_cluster259_sector001_macro"
x=-61043796 
y=16218576 
z=-76501824
          
[[offset]]
cluster = "tpthree_cluster1260_macro"
name = "tpthree_cluster1260_sector001_macro"
x=158896064 
y=26536176 
z=-70680608
          
[[offset]]
cluster = "tpthree_cluster1273_macro"
name = "tpthree_cluster1273_sector001_macro"
x=-166574160 
y=8139696 
z=-103367112
          
[[offset]]
cluster = "tpthree_cluster274_macro"
name = "tpthree_cluster274_sector001_macro"
x=35353520 
y=-98864921 
z=-91813304
          
[[offset]]
cluster = "tpthree_cluster289_macro"
name = "tpthree_cluster289_sector001_macro"
x=-17377328 
y=-42546308 
z=-7709056
          
[[offset]]
cluster = "tpthree_cluster1292_macro"
name = "tpthree_cluster1292_sector001_macro"
x=2782352 
y=-2376656 
z=-114311528
          
[[offset]]
cluster = "tpthree_cluster293_macro"
name = "tpthree_cluster293_sector001_macro"
x=-186100620 
y=84887712 
z=-102560088
          
[[offset]]
cluster = "tpthree_cluster295_macro"
name = "tpthree_cluster295_sector001_macro"
x=-134992628 
y=-82483284 
z=19693248
          
[[offset]]
cluster = "tpthree_cluster296_macro"
name = "tpthree_cluster296_sector001_macro"
x=71412832 
y=-57288720 
z=-112443144
          
[[offset]]
cluster = "tpthree_cluster314_macro"
name = "tpthree_cluster314_sector001_macro"
x=-183412857 
y=82199440 
z=-48812336
          
[[offset]]
cluster = "tpthree_cluster331_macro"
name = "tpthree_cluster331_sector001_macro"
x=-126023152 
y=26756144 
z=-163211544
          
[[offset]]
cluster = "tpthree_cluster371_macro"
name = "tpthree_cluster371_sector001_macro"
x=1593680 
y=-43369192 
z=87186912
          
[[offset]]
cluster = "tpthree_cluster384_macro"
name = "tpthree_cluster384_sector001_macro"
x=15829968 
y=-60026856 
z=-151842192
          
[[offset]]
cluster = "tpthree_cluster390_macro"
name = "tpthree_cluster390_sector001_macro"
x=24656064 
y=64414640 
z=-178052028
          
[[offset]]
cluster = "tpthree_cluster050_macro"
name = "tpthree_cluster050_sector001_macro"
x=-58970960 
y=-44734616 
z=-45795920
          
[[offset]]
cluster = "tpthree_cluster051_macro"
name = "tpthree_cluster051_sector001_macro"
x=57197664 
y=95941344 
z=-98071096
          
[[offset]]
cluster = "tpthree_cluster069_macro"
name = "tpthree_cluster069_sector001_macro"
x=51158688 
y=28501688 
z=74685056
          
[[offset]]
cluster = "tpthree_cluster070_macro"
name = "tpthree_cluster070_sector001_macro"
x=-3632416 
y=-36364656 
z=172817920
          
[[offset]]
cluster = "tpthree_cluster145_macro"
name = "tpthree_cluster145_sector001_macro"
x=51914096 
y=72743648 
z=-59546720
          
[[offset]]
cluster = "tpthree_cluster165_macro"
name = "tpthree_cluster165_sector001_macro"
x=-167857034 
y=-96874166 
z=-105917224
          
[[offset]]
cluster = "tpthree_cluster166_macro"
name = "tpthree_cluster166_sector001_macro"
x=33991936 
y=72336656 
z=-90509960
          
[[offset]]
cluster = "tpthree_cluster184_macro"
name = "tpthree_cluster184_sector001_macro"
x=69203712 
y=-52038475 
z=4882192
          
[[offset]]
cluster = "tpthree_cluster197_macro"
name = "tpthree_cluster197_sector001_macro"
x=148480192 
y=-33109860 
z=74397056
          
[[offset]]
cluster = "tpthree_cluster216_macro"
name = "tpthree_cluster216_sector001_macro"
x=6942080 
y=91488160 
z=73872032
          
[[offset]]
cluster = "tpthree_cluster235_macro"
name = "tpthree_cluster235_sector001_macro"
x=-34851424 
y=-44838832 
z=187407552
          
[[offset]]
cluster = "tpthree_cluster236_macro"
name = "tpthree_cluster236_sector001_macro"
x=-118833264 
y=-71027594 
z=-160784088
          
[[offset]]
cluster = "tpthree_cluster343_macro"
name = "tpthree_cluster343_sector001_macro"
x=-63414144 
y=63934096 
z=102277120
          
[[offset]]
cluster = "tpthree_cluster363_macro"
name = "tpthree_cluster363_sector001_macro"
x=32843904 
y=-97384106 
z=4769056
          
[[offset]]
cluster = "tpthree_cluster364_macro"
name = "tpthree_cluster364_sector001_macro"
x=136182560 
y=-911192 
z=-149426256
          
[[offset]]
cluster = "tpthree_cluster365_macro"
name = "tpthree_cluster365_sector001_macro"
x=92429600 
y=-69241360 
z=-39830560
          
[[offset]]
cluster = "tpthree_cluster011_macro"
name = "tpthree_cluster011_sector001_macro"
x=-4097984 
y=-99487166 
z=56595424
          
[[offset]]
cluster = "tpthree_cluster030_macro"
name = "tpthree_cluster030_sector001_macro"
x=-3421360 
y=96047584 
z=29093248
          
[[offset]]
cluster = "tpthree_cluster031_macro"
name = "tpthree_cluster031_sector001_macro"
x=-76531800 
y=36511056 
z=114759872
          
[[offset]]
cluster = "tpthree_cluster140_macro"
name = "tpthree_cluster140_sector001_macro"
x=196858592 
y=54698192 
z=123481568
          
[[offset]]
cluster = "tpthree_cluster158_macro"
name = "tpthree_cluster158_sector001_macro"
x=33202960 
y=66357744 
z=63609952
          
[[offset]]
cluster = "tpthree_cluster159_macro"
name = "tpthree_cluster159_sector001_macro"
x=-144193240 
y=51799696 
z=-14788288
          
[[offset]]
cluster = "tpthree_cluster189_macro"
name = "tpthree_cluster189_sector001_macro"
x=109779968 
y=-8142976 
z=-184602998
          
[[offset]]
cluster = "tpthree_cluster225_macro"
name = "tpthree_cluster225_sector001_macro"
x=-20105632 
y=-52959792 
z=109040896
          
[[offset]]
cluster = "tpthree_cluster349_macro"
name = "tpthree_cluster349_sector001_macro"
x=193083872 
y=-69566276 
z=176852224
          
[[offset]]
cluster = "tpthree_cluster366_macro"
name = "tpthree_cluster366_sector001_macro"
x=-124276272 
y=11716840 
z=-48909968
          
[[offset]]
cluster = "tpthree_cluster367_macro"
name = "tpthree_cluster367_sector001_macro"
x=-58337136 
y=-52593656 
z=136524544
          
[[offset]]
cluster = "tpthree_cluster044_macro"
name = "tpthree_cluster044_sector001_macro"
x=-87194320 
y=27887176 
z=-191928753
          
[[offset]]
cluster = "tpthree_cluster060_macro"
name = "tpthree_cluster060_sector001_macro"
x=139538944 
y=-91287403 
z=-149479216
          
[[offset]]
cluster = "tpthree_cluster061_macro"
name = "tpthree_cluster061_sector001_macro"
x=53414368 
y=65536848 
z=989200
          
[[offset]]
cluster = "tpthree_cluster062_macro"
name = "tpthree_cluster062_sector001_macro"
x=-68617416 
y=74738704 
z=151820608
          
[[offset]]
cluster = "tpthree_cluster079_macro"
name = "tpthree_cluster079_sector001_macro"
x=159871040 
y=40990048 
z=144115712
          
[[offset]]
cluster = "tpthree_cluster080_macro"
name = "tpthree_cluster080_sector001_macro"
x=-96406200 
y=23872400 
z=1308512
          
[[offset]]
cluster = "tpthree_cluster220_macro"
name = "tpthree_cluster220_sector001_macro"
x=-166058344 
y=69803104 
z=16662400
          
[[offset]]
cluster = "tpthree_cluster221_macro"
name = "tpthree_cluster221_sector001_macro"
x=151906976 
y=-70060146 
z=56243616
          
[[offset]]
cluster = "tpthree_cluster240_macro"
name = "tpthree_cluster240_sector001_macro"
x=-52677072 
y=59003312 
z=-140863496
          
[[offset]]
cluster = "tpthree_cluster241_macro"
name = "tpthree_cluster241_sector001_macro"
x=67201072 
y=-611626 
z=-123929784
          
[[offset]]
cluster = "tpthree_cluster260_macro"
name = "tpthree_cluster260_sector001_macro"
x=28349376 
y=22697056 
z=-146303756
          
[[offset]]
cluster = "tpthree_cluster261_macro"
name = "tpthree_cluster261_sector001_macro"
x=-38343888 
y=-86620058 
z=185127552
          
[[offset]]
cluster = "tpthree_cluster262_macro"
name = "tpthree_cluster262_sector001_macro"
x=34843920 
y=-73592984 
z=-48148208
          
[[offset]]
cluster = "tpthree_cluster273_macro"
name = "tpthree_cluster273_sector001_macro"
x=-134327920 
y=-19435152 
z=196101600
          
[[offset]]
cluster = "tpthree_cluster281_macro"
name = "tpthree_cluster281_sector001_macro"
x=43465472 
y=-84529950 
z=105538464
          
[[offset]]
cluster = "tpthree_cluster290_macro"
name = "tpthree_cluster290_sector001_macro"
x=105782656 
y=36423136 
z=87082016
          
[[offset]]
cluster = "tpthree_cluster291_macro"
name = "tpthree_cluster291_sector001_macro"
x=67195088 
y=-40350472 
z=155766976
          
[[offset]]
cluster = "tpthree_cluster292_macro"
name = "tpthree_cluster292_sector001_macro"
x=-113787528 
y=44648640 
z=-93874768
          
[[offset]]
cluster = "tpthree_cluster311_macro"
name = "tpthree_cluster311_sector001_macro"
x=171973792 
y=-53980552 
z=-185723524
          
[[offset]]
cluster = "tpthree_cluster312_macro"
name = "tpthree_cluster312_sector001_macro"
x=-174452562 
y=88907168 
z=6785328
          
[[offset]]
cluster = "tpthree_cluster330_macro"
name = "tpthree_cluster330_sector001_macro"
x=-187676750 
y=56182176 
z=-95028736
          